version: "3.8"
services:

  # PHP service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    command:
      - php
      - base.php