services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      PHP_MEMORY_LIMIT: 1024M
    ports:
      - "8080:80"
